feat: new permissions model
artipie/conda-adapter pull request #103
Opened 2023-03-02 14:21 UTC by olenagerasimova

closes #102

2023-03-02 15:30 UTC, dgarus requested changes
@olenagerasimova thanks!
Minor comment

2023-03-02 15:30 UTC, dgarus commented on src/main/java/com/artipie/conda/http/CondaSlice.java
> +        this(storage, Policy.FREE, Authentication.ANONYMOUS, CondaSlice.ANONYMOUS, url, "test");
Suggest to change `test` to `*`

2023-03-02 15:30 UTC, dgarus commented on src/main/java/com/artipie/conda/http/CondaSlice.java
> +    public CondaSlice(final Storage storage, final Policy<?> policy, final Authentication users,
As I understand, we have a separate slice for every repo. 
Is it true?

2023-03-03 08:02 UTC, olenagerasimova commented on src/main/java/com/artipie/conda/http/CondaSlice.java
> +    public CondaSlice(final Storage storage, final Policy<?> policy, final Authentication users,
yes, there is an entry-point slice in each adapter. In artipie these adapter slices created in `SliceFromConfig` class

2023-03-03 08:05 UTC, olenagerasimova commented
@dgarus thanks, fixed

2023-03-03 08:25 UTC, dgarus approved these changes
Thanks!

2023-03-03 08:25 UTC, merged