`.conda` packages in `repodata.json`
artipie/conda-adapter pull request #12
Opened 2021-07-14 10:49 UTC by olenagerasimova

Part of #5 
It appears that .tar.bz2 and .conda packages are separated, the `repodata.json` format is:
```
{ 
  packages: { \\all tar.bz2 packages listed here\\ },
  packages.conda { \\all .conda packages listed here\\ }
}
```
I've updated readme, corrected classes and tests.

2021-07-14 12:05 UTC, g4s8 requested changes
@olenagerasimova please check my comments

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/CondaRepodataRemoveTest.java
> +                        ",\"packages.conda\":{}}"
Checking JSON against string representation is not really robust: e.g. this test can break in case of library updates or CI system environment changes, when JSON library produces the same valid JSON object but change encoding or formatting. I'd recommend using json matchers like in other adapters

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/meta/JsonMaidTest.java
> +                    "}"
And same here. Aside from it, this assertion is hard to read and understand.

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/meta/JsonMaidTest.java
> +                    "  }", "}"
And same here

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/meta/JsonMaidTest.java
> +                    "  \"packages.conda\" : { }",
And here

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/meta/JsonMaidTest.java
> +    private String cram() {
This method could be converted to `private static final String` field - it's always the same

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/meta/JsonMaidTest.java
> +    private String decorator() {
This method is also could be refactored to field

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/meta/JsonMaidTest.java
> +    private String pyqt() {
And this method

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/meta/JsonMaidTest.java
> +    private String notebook() {
And this method. Maybe it'd be easier to maintain some test resources with JSON files instead of putting JSON data into test code, WDYT?

2021-07-14 12:05 UTC, g4s8 commented on src/test/com/artipie/conda/meta/JsonMaidTest.java
> +    private String tenacity() {
Same here

2021-07-14 12:45 UTC, olenagerasimova commented
@g4s8 thanks, I've added dependency to compare jsons (in our case - ignoring formatting and order) and extracted files for `JsonMaidTest` assertions. As for `CondaRepodata` I think it's ok to leave resulting json as is in the assertion.

2021-07-15 08:10 UTC, olenagerasimova commented
@g4s8 please, take a look, I need it merged to continue the work

2021-07-15 09:05 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-07-15 09:06 UTC, merged