Added conda upload skeleton
artipie/conda-adapter pull request #38
Opened 2021-08-06 15:05 UTC by olenagerasimova

Part of #32 
Added slices skeleton for anaconda upload process. The process ends with the server returning format of the requests to upload packages to amazon (check `PostStageCommitSlice`). 
I do not know how to handle this situation yet, not sure this PR is supposed to be merged as is.

2021-08-06 15:06 UTC, olenagerasimova commented
@g4s8 please, take a look and let me know what do you think.

2021-08-09 07:20 UTC, g4s8 requested changes
@olenagerasimova please check my comments

2021-08-09 07:20 UTC, g4s8 commented on src/main/java/com/artipie/conda/http/CondaSlice.java
> +        final String url) {
Maybe it's possible to extract application URL from `Host` header?

2021-08-09 07:20 UTC, g4s8 commented on src/main/java/com/artipie/conda/http/DownloadRepodataSlice.java
> +                                                ).getBytes(StandardCharsets.US_ASCII)
Why did you construct JSON manually instead of using `JsonBuilder` + `RsJson`? It can automatically escape field values in case of `"`

2021-08-09 07:20 UTC, g4s8 commented on src/main/java/com/artipie/conda/http/GetPackageSlice.java
> +                        "{\"error\": \"\\\"%s\\\" could not be found\"}",
And same here: a lot of escaping (e.g. `\"\\\"%s\\\"`) is hard to read, maybe you can use `JsonBuilder` here?

2021-08-09 07:34 UTC, olenagerasimova commented on src/main/java/com/artipie/conda/http/CondaSlice.java
> +        final String url) {
hm, `conda-client` passes `Host: host.testcontainers.internal:58952`, but I am not sure if that's the best way and we already have corresponding setting in our yamls and settings structure.

2021-08-09 07:44 UTC, olenagerasimova commented on src/main/java/com/artipie/conda/http/DownloadRepodataSlice.java
> +                                                ).getBytes(StandardCharsets.US_ASCII)
used `JsonBuilder`, `RsJson` is not suitable here as I should return an attachment

2021-08-09 07:48 UTC, olenagerasimova commented
@g4s8 thanks, corrected and answered

2021-08-09 08:51 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-08-09 09:01 UTC, merged