Implemented reading file from multipart body on upload
artipie/conda-adapter pull request #48
Opened 2021-08-31 08:53 UTC by olenagerasimova

Part of #32 
Fully implemented `UpdateSlice`:
- added method to obtain new package from multipart body
- corrected unit and integration tests accordingly
- added slice to conda main http entry point

2021-08-31 10:38 UTC, g4s8 requested changes
@olenagerasimova please see my question

2021-08-31 10:38 UTC, g4s8 commented on src/main/java/com/artipie/conda/http/UpdateSlice.java
> +        ).flatMap(part -> part);
I'm not sure if it's possible here, but it would be good to return `Content` built from `Content-Length` header of part.

2021-08-31 15:49 UTC, olenagerasimova commented
@g4s8 I've added todo with your suggestion, let's discuss possible implementation later and try to fix todo

2021-09-01 09:54 UTC, olenagerasimova commented
@g4s8 please take a look/merge

2021-09-01 13:44 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-09-01 14:29 UTC, merged