Added skeleton for remove operation
artipie/conda-adapter pull request #6
Opened 2021-07-08 10:12 UTC by olenagerasimova

Part of #5 
Added interface/class for remove operation, just a skeleton for now.

2021-07-08 10:37 UTC, genryxy reviewed
@olenagerasimova thanks, looks good to me
@g4s8 could you please take a look at this one

2021-07-08 10:42 UTC, g4s8 requested changes
@olenagerasimova please check my comments/questions

2021-07-08 10:42 UTC, g4s8 commented on src/main/java/com/artipie/conda/CondaRepodata.java
> +public interface CondaRepodata {
Why do we need empty interface?

2021-07-08 10:42 UTC, g4s8 commented on src/main/java/com/artipie/conda/CondaRepodata.java
> +        public Remove(final InputStream input, final OutputStream out) {
So you are going to block thread on repository update, isn't it possible to avoid blocking here?

2021-07-08 10:54 UTC, olenagerasimova commented on src/main/java/com/artipie/conda/CondaRepodata.java
> +        public Remove(final InputStream input, final OutputStream out) {
SDK will not be reactive, our colleagues work with input/output streams.

2021-07-08 10:59 UTC, olenagerasimova commented on src/main/java/com/artipie/conda/CondaRepodata.java
> +public interface CondaRepodata {
Strictly speaking - we do not need it, this interface is some kind of holder for operations with repodata. Later I'll add class to append packages info into repodata file. Also, it seems to me that the way internal classes are created and used `CondaRepodata .Remove()...` and `CondaRepodata.Append()...` is clear and easy to read/understand.

2021-07-08 11:55 UTC, olenagerasimova commented
@g4s8 please, check the answers

2021-07-09 09:24 UTC, g4s8 commented on src/main/java/com/artipie/conda/CondaRepodata.java
> +        public Remove(final InputStream input, final OutputStream out) {
@olenagerasimova then maybe we can create blocking wrappers around reactive SDK? If the metadata of the repository are JSON formatted, then it could be parsed directly from storage using JSON stream parsers without saving to temporary files. But if custerms needs IO stream API, we can provide wrappers to hide storage behind this wrapper

2021-07-09 10:07 UTC, olenagerasimova commented on src/main/java/com/artipie/conda/CondaRepodata.java
> +        public Remove(final InputStream input, final OutputStream out) {
@g4s8 hm, storage is higher level abstraction than input/output streams and as JSON stream API works with streams, we will need to convert content into streams (using rio). So, as I plan, we will still use this implementation in artipie, on the lower level of working with storage/content.

2021-07-09 10:13 UTC, g4s8 commented on src/main/java/com/artipie/conda/CondaRepodata.java
> +        public Remove(final InputStream input, final OutputStream out) {
I see, let's go this way

2021-07-09 10:13 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-07-09 10:18 UTC, olenagerasimova commented
@g4s8 please merge, I do not have rights here (even after approval)

2021-07-09 11:14 UTC, g4s8 commented
@olenagerasimova can you please check now?

2021-07-09 12:01 UTC, merged

2021-07-09 12:01 UTC, olenagerasimova commented
@g4s8 thanks, all good now