Added skeleton to manage tokens in asto
artipie/conda-adapter pull request #62
Opened 2021-09-15 10:40 UTC by olenagerasimova

Part of #57 
Added `Tokens` interface and asto implementation, skeleton to manage tokens in asto.

2021-09-15 11:13 UTC, olenagerasimova commented
@g4s8 please, take a look, that's just a skeleton, what do you say about design?

2021-09-17 07:58 UTC, g4s8 requested changes
@olenagerasimova please check my comments

2021-09-17 07:58 UTC, g4s8 commented on src/main/java/com/artipie/conda/Tokens.java
> +        private final Date expire;
I'd use `Instant` here, as a replacement for `Date`. Old date API could be deprecated soon

2021-09-17 07:58 UTC, g4s8 commented on src/main/java/com/artipie/conda/Tokens.java
> +    final class TokenItem {
Why this class don't have any method?

2021-09-17 08:59 UTC, olenagerasimova commented
@g4s8 thanks, made changes, take a look please

2021-09-17 10:31 UTC, g4s8 approved these changes
@olenagerasimova thanks, looks good

2021-09-17 11:57 UTC, merged