Implemented removing tokens in `DeleteTokenSlice`
artipie/conda-adapter pull request #73
Opened 2021-09-30 06:38 UTC by olenagerasimova

Part of #57 
Added `AuthTokens` to `DeleteTokenSlice`, removed old tokens map, corrected test for `DeleteTokenSlice` and enabled IT.

2021-09-30 07:56 UTC, g4s8 requested changes
@olenagerasimova just one comment

2021-09-30 07:56 UTC, g4s8 commented on src/main/java/com/artipie/conda/http/DeleteTokenSlice.java
> +                    if (tkn.isPresent()) {
You can simplify this to `tkn.map(token -> this.tokens.remove(token).thenApply(...)).orElse(new RsWithHeaders(UNAUTHORIZED))`

2021-09-30 08:51 UTC, olenagerasimova commented
@g4s8 thanks, fixed

2021-10-01 06:47 UTC, olenagerasimova commented
@g4s8 please, check

2021-10-01 07:46 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-10-01 08:27 UTC, merged