fix(UpdateSlice): remove dot in temp key
artipie/conda-adapter pull request #84
Opened 2022-02-18 20:15 UTC by baudoliver7

Given that dot is not a valid key part, we removed it in the temporary
upload key `TMP`.

Cc: https://github.com/artipie/asto/pull/402#issuecomment-1044465257
Ref: artipie/artipie#995

2022-02-18 21:29 UTC, baudoliver7 commented
@artipie/maintainers need a review here :)

2022-02-22 07:13 UTC, olenagerasimova requested changes
@baudoliver7 dot is actually not a problem, `/` is, so I'd suggest to keep the dot

2022-02-23 05:38 UTC, baudoliver7 commented
> @baudoliver7 dot is actually not a problem, `/` is, so I'd suggest to keep the dot

@olenagerasimova Thanks. Fixed

2022-02-24 05:41 UTC, olenagerasimova approved these changes
@baudoliver7 thanks

2022-02-24 05:41 UTC, merged